org.nrg.Feature=container-service-log-access
org.nrg.Feature.container-service-log-access.key=container-service-log-access
org.nrg.Feature.container-service-log-access.name=Access of log files created by a Container run
org.nrg.Feature.container-service-log-access.OnByDefault=false
org.nrg.Feature.container-service-log-access.description=Allow access to log files created by a Container runs by other users within the project