---
include:
  - project: flywheel-io/infrastructure/ci-templates
    ref: master
    file: security-scans.yml
  - template: Jobs/SAST.gitlab-ci.yml

gemnasium-maven-dependency_scanning:
  variables:
    DS_JAVA_VERSION: 8

variables:
  SAST_EXCLUDED_PATHS: "spec, test, tests, tmp, swagger.json"
  
sast:
  variables:
    SAST_EXCLUDED_PATHS: "$SAST_EXCLUDED_PATHS"
  stage: test



