#######################################################
####  Root Project Settings Spawner Config Object  ####
#######################################################


projectCommandConfigsPanel:
    kind: panel
    name: projectCommandConfigsPanel
    label: Project Command Configurations
    footer: false
    contents:
        projCommandConfigDescription:
            tag: div.message
            contents:
                "This panel lists all enabled commands from all installed images, and allows project owners to define a custom configuration for each command. This configuration will be used by default by all users in this project, but users can override certain parameters."
        projCommandConfigListContainer:
            tag: "div#proj-command-config-list-container"
        projCommandConfigTemplate:
            tag: "div#proj-command-config-template.html-template"
            contents:
                projConfigViewer:
                    kind: panel
                    name: projConfigViewer
                    id: proj-config-viewer
                    header: false
                    footer: false
        projCommandHistoryScript:
            tag: script|src="~/scripts/xnat/plugin/containerService/containerService-history.js"
        projCommandConfigScript:
            tag: script|src="~/scripts/xnat/plugin/containerService/containerService-projectSettings.js"
        jqueryUi:
            tag: script|src="~/scripts/lib/jquery-ui/jquery-ui.min.js"
        projCommandStylesheet:
            tag: link|rel="stylesheet"|type="text/css"|href="~/scripts/xnat/plugin/containerService/containerConfig.css"
        tableStyle:
            tag: link|rel="stylesheet"|type="text/css"|href="~/scripts/xnat/app/scanTable/scanTable.css"
        jqueryUiCss:
            tag: link|rel="stylesheet"|type="text/css"|href="~/scripts/lib/jquery-ui/jquery-ui.css"

projectCommandAutomationPanel:
    kind: panel
    name: projectCommandAutomationPanel
    label: Command Automation
    contents:
        projectCommandAutomationNote:
            tag: div.message
            contents:
                "With this panel, you can set up an automated command execution that will be triggered by an XNAT event, such as an image session being archived."
        projectCommandAutomationSetup:
            kind: panel.input.button
            id:
        projectCommandAutomationTable:
            tag: div#command-automation-list
            contents: No commands defined

projectCommandOrchestrationPanel:
    kind: panel
    name: projectCommandOrchestrationPanel
    label: Command Orchestration
    contents:
        projectCommandOrchestrationNote:
            tag: div.message
            contents:
                "Setup orchestration of multiple commands, which will run sequentially as long as predecessors complete without error."
        projectCommandOrchestrationTable:
            tag: div#command-orchestration
            contents: Loading...

projectCommandHistoryPanel:
    kind: panel
    label: Command History
    contents:
        projectCommandHistoryTableContainer:
            tag: div.tab-container
            contents:
                dataTableContainer:
                    tag: div#command-history-container.data-table-wrapper.clean
                    contents: Loading history entries...


projectSettings:
    kind: tabs
    name: projectSettingsPage
    label: Project Settings for Container Service
    meta:
        tabGroups:
            containerServiceProjectTabGroup: Container Service
    contains: tabs
    tabs:
        projectCommandConfigurationTab:
            kind: tab
            label: Configure Commands
            group: containerServiceProjectTabGroup
            active: true
            contents:
                ${projectCommandConfigsPanel}
        projectCommandAutomationTab:
            kind: tab
            label: Command Automation
            group: containerServiceProjectTabGroup
            active: false
            contents:
                ${projectCommandAutomationPanel}
        projectCommandOrchestrationTab:
            kind: tab
            label: Command Orchestration
            group: containerServiceProjectTabGroup
            active: false
            contents:
                ${projectCommandOrchestrationPanel}
        projectCommandHistoryTab:
            kind: tab
            label: Command History
            group: containerServiceProjectTabGroup
            active: false
            contents:
                ${projectCommandHistoryPanel}