#######################################################
####  Root Project Settings Spawner Config Object  ####
#######################################################


projectCommandConfigsPanel:
    kind: panel
    name: projectCommandConfigsPanel
    label: Project Command Configurations
    footer: false
    contents:
        projCommandConfigDescription:
            tag: "p"
            contents:
                "This panel lists all enabled commands from all installed images, and allows project owners to define a custom configuration for each command. This configuration will be used by default by all users in this project, but users can override certain parameters."
        projCommandConfigListContainer:
            tag: "div#proj-command-config-list-container"
        projCommandConfigTemplate:
            tag: "div#proj-command-config-template.html-template"
            contents:
                projConfigViewer:
                    kind: panel
                    name: projConfigViewer
                    id: proj-config-viewer
                    header: false
                    footer: false
        projCommandConfigScript:
#           tag: script|src="/scripts/xnat/plugin/containerService/containerServices-projectSettings.js"
            tag: script|src="~/scripts/xnat/plugin/containerService/containerServices-projectSettings.js"
        projCommandStylesheet:
        #   tag: link|rel="stylesheet"|type="text/css"|href="/scripts/xnat/plugin/containerService/containerConfig.css"
            tag: link|rel="stylesheet"|type="text/css"|href="~/scripts/xnat/plugin/containerService/containerConfig.css"

projectCommandAutomationPanel:
    kind: panel
    name: projectCommandAutomationPanel
    label: Command Automation
    contents:
        projectCommandAutomationNote:
            tag: div.message
            contents:
                "With this panel, you can set up an automated command execution that will be triggered by an XNAT event, such as an image session being archived."
        projectCommandAutomationSetup:
            kind: panel.input.button
            id:
        projectCommandAutomationTable:
            tag: div#command-automation-list
            contents: Table will go here


projectSettings:
    kind: tabs
    name: projectSettingsPage
    label: Project Settings for Container Service
    meta:
        tabGroups:
            containerServiceProjectTabGroup: Container Service
    contains: tabs
    tabs:
        commandConfigurationTab:
            kind: tab
            name: commandProjectConfig
            label: Configure Commands
            group: containerServiceProjectTabGroup
            active: true
            contents:
                ${projectCommandConfigsPanel}
        commandAutomationTab:
            kind: tab
            name: commandAutomationTab
            label: Command Automation
            group: containerServiceProjectTabGroup
            active: false
            contents:
                ${projectCommandAutomationPanel}