#######################################################
####  Root Project Settings Spawner Config Object  ####
#######################################################

projectCommandConfigsPanel:
    kind: panel
    name: projectCommandConfigsPanel
    label: Project Command Configurations
    footer: false
    contents:
        projCommandConfigDescription:
            tag: "p"
            contents:
                "This panel lists all enabled commands from all installed images, and allows project owners to define a custom configuration for each command. This configuration will be used by default by all users in this project, but users can override certain parameters."
        projCommandConfigListContainer:
            tag: "div#proj-command-config-list-container"
        projCommandConfigTemplate:
            tag: "div#proj-command-config-template.html-template"
            contents:
                projConfigViewer:
                    kind: panel
                    name: projConfigViewer
                    id: proj-config-viewer
                    header: false
                    footer: false
        projCommandConfigScript:
#           tag: script|src="/scripts/xnat/plugin/containerService/projCommandConfigManagement.js"
            tag: script|src="~/scripts/xnat/plugin/containerService/projCommandConfigManagement.js"

projectCommandProjectPrefs:
    kind: panel
    label: Site-wide Preferences for Project Command Use
    footer: false
    contents:
        projectCommandProjectPrefsDesc:
            tag: "p"
            contents:
                "This setting allows you to choose whether to \"opt-in\" or \"opt-out\" of all commands that are enabled at the site-wide level."
        spacer:
            tag: "hr|color=#ccc"
        projectCommandPrefsFormContainer:
            tag: "div#project-command-prefs-form-container"
        projectOptIntoSitewideCommands:
            kind: panel.input.switchbox
            id: optIntoSitewideCommands
            value: true
            label: Enable Site-wide Commands By Default?
            onText: Opt-IN To Enabled Site-wide Commands
            offText: Opt-OUT Of Enabled Site-wide Commands
            description: "If set to \"Opt-OUT,\" each project will either have to enable each command individually, or change their project opt-in setting."

projectSettings:
    kind: tabs
    name: projectSettingsPage
    label: Project Settings for Container Service
    meta:
        tabGroups:
            containerServiceProjectTabGroup: Container Service
    contains: tabs
    tabs:
        commandConfigurationTab:
            kind: tab
            name: commandProjectConfig
            label: Configure Commands
            group: containerServiceProjectTabGroup
            active: true
            contents:
                ${projectCommandProjectPrefs}
                ${projectCommandConfigsPanel}