version: 2
jobs:
    build:
        working_directory: ~/container-service
        docker:
            - image: circleci/openjdk:8
        steps:
            - checkout
            - restore_cache:
                  key: cache-{{ .Branch }}-{{ checksum "build.gradle" }}
            - run:
                name: Refresh dependencies
                command: ./gradlew --refresh-dependencies dependencies
            - run:
                name: Compile
                command: ./gradlew compileJava compileTestJava
            - save_cache:
                  key: cache-{{ .Branch }}-{{ checksum "build.gradle" }}
                  paths:
                      - ~/.gradle
            - setup_remote_docker
            - run:
                name: Run tests
                command: ./gradlew test
            - store_test_results:
                path: build/test-results/
            - store_artifacts:
                path: build/reports/tests/
